<instruction>      ::= <version_decl> [<selectors_block>] {<component_block>} ;

<version_decl>     ::= "JKSPEC" <scalar> ;

<selectors_block>  ::= "SELECTORS" "{" {<kv_stmt>} "}" ;

<component_block>  ::= "COMPONENT" <string> <string> "{" {<component_stmt>} "}" ;
<component_stmt>   ::= <profile_block> | <augmentations_block> | <active_profile_stmt> ;
<active_profile_stmt> ::= "ACTIVE_PROFILE" ":" <scalar> ;

<profile_block>    ::= "PROFILE" <string> "{" {<profile_stmt>} "}" ;
<profile_stmt>     ::= <optimizer_block>
                     | <lr_scheduler_block>
                     | <loss_block>
                     | <component_params_block>
                     | <reproducibility_block>
                     | <numerics_block>
                     | <gradient_block>
                     | <checkpoint_block>
                     | <metrics_block>
                     | <data_ref_block> ;

<optimizer_block>      ::= "OPTIMIZER" <string> "{" {<kv_stmt>} "}" ;
<lr_scheduler_block>   ::= "LR_SCHEDULER" <string> "{" {<kv_stmt>} "}" ;
<loss_block>           ::= "LOSS" <string> "{" {<kv_stmt>} "}" ;
<component_params_block> ::= "COMPONENT_PARAMS" "{" {<kv_stmt>} "}" ;
<reproducibility_block>  ::= "REPRODUCIBILITY" "{" {<kv_stmt>} "}" ;
<numerics_block>         ::= "NUMERICS" "{" {<kv_stmt>} "}" ;
<gradient_block>         ::= "GRADIENT" "{" {<kv_stmt>} "}" ;
<checkpoint_block>       ::= "CHECKPOINT" "{" {<kv_stmt>} "}" ;
<metrics_block>          ::= "METRICS" "{" {<kv_stmt>} "}" ;
<data_ref_block>         ::= "DATA_REF" "{" {<kv_stmt>} "}" ;

<augmentations_block> ::= "AUGMENTATIONS" <string> "{" {<curve_block>} "}" ;
<curve_block>         ::= "CURVE" <string> "{" {<kv_stmt>} "}" ;

<kv_stmt>           ::= <identifier> ":" <value> ;
<value>             ::= <scalar> | <array> ;
<array>             ::= "[" [<scalar> {"," <scalar>}] "]" ;

<scalar>            ::= <string> | <identifier> ;

<string>            ::= "\"" {<string_char>} "\"" ;
<string_char>       ::= <identifier_char> | <space_char> | <symbol_char> ;

<identifier>        ::= <identifier_char> {<identifier_char> | <number> | <symbol_char>} ;
<identifier_char>   ::= <letter> | "_" ;
<space_char>        ::= " " | "\t" ;
<symbol_char>       ::= "." | "," | ":" | ";" | "-" | "_" | "\\" | "/" | "=" | "@" ;
<letter>            ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ;
<number>            ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
