<instruction>            ::= {<wave>} ;

<wave>                   ::= "WAVE" [<whitespace>] <wave_name> [<whitespace>] "{"
                             <line_end>
                             {<wave_stmt>}
                             [<whitespace>] "}" <line_end> ;

<wave_stmt>              ::= [<whitespace>] <wave_stmt_core> ;
<wave_stmt_core>         ::= <mode_assignment>
                           | <determinism_assignment>
                           | <sampler_assignment>
                           | <epochs_assignment>
                           | <batch_size_assignment>
                           | <max_batches_per_epoch_assignment>
                           | <wikimyei_block>
                           | <source_block>
                           | <probe_block>
                           | <sink_block> ;

<assign>                 ::= [<whitespace>] (":" | "=") [<whitespace>] ;

<mode_assignment>        ::= "MODE" <assign> <mode_value> [<whitespace>] ";" <line_end> ;
<determinism_assignment> ::= "DETERMINISM" <assign> <determinism_value> [<whitespace>] ";" <line_end> ;
<sampler_assignment>     ::= "SAMPLER" <assign> <sampler_value> [<whitespace>] ";" <line_end> ;
<epochs_assignment>      ::= "EPOCHS" <assign> <unsigned_int> [<whitespace>] ";" <line_end> ;
<batch_size_assignment>  ::= "BATCH_SIZE" <assign> <unsigned_int> [<whitespace>] ";" <line_end> ;
<max_batches_per_epoch_assignment> ::= "MAX_BATCHES_PER_EPOCH" <assign> <unsigned_int> [<whitespace>] ";" <line_end> ;

<binding_ref>            ::= "<" [<whitespace>] <id_value> [<whitespace>] ">" ;

<wikimyei_block>         ::= "WIKIMYEI" [<whitespace>] [":" [<whitespace>]] <binding_ref> [<whitespace>] "{"
                             <line_end>
                             {<wikimyei_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<wikimyei_assignment>    ::= [<whitespace>] <wikimyei_assignment_core> ;
<wikimyei_assignment_core> ::= <family_assignment>
                             | <hashimyei_assignment>
                             | <path_assignment>
                             | <jkimyei_block> ;
<jkimyei_block>          ::= "JKIMYEI" <assign> "{" <line_end>
                             [<whitespace>] "HALT_TRAIN" <assign> <bool_value> [<whitespace>] ";" <line_end>
                             [<whitespace>] "PROFILE_ID" <assign> <id_value> [<whitespace>] ";" <line_end>
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;

<source_block>           ::= "SOURCE" [<whitespace>] [":" [<whitespace>]] <binding_ref> [<whitespace>] "{"
                             <line_end>
                             {<source_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<source_assignment>      ::= [<whitespace>] <source_assignment_core> ;
<source_assignment_core> ::= <family_assignment>
                           | <path_assignment>
                           | <source_settings_block>
                           | <source_runtime_block> ;
<source_settings_block>  ::= "SETTINGS" <assign> "{" <line_end>
                             {<source_settings_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<source_settings_assignment> ::= [<whitespace>] <source_settings_assignment_core> ;
<source_settings_assignment_core> ::= <sampler_assignment>
                                    | <source_workers_assignment>
                                    | <source_force_rebuild_cache_assignment>
                                    | <source_range_warn_batches_assignment> ;
<source_runtime_block>   ::= "RUNTIME" <assign> "{" <line_end>
                             {<source_runtime_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<source_runtime_assignment> ::= [<whitespace>] <source_runtime_assignment_core> ;
<source_runtime_assignment_core> ::= <source_symbol_assignment>
                                   | <source_from_assignment>
                                   | <source_to_assignment>
                                   | <source_sources_dsl_file_assignment>
                                   | <source_channels_dsl_file_assignment> ;
<source_symbol_assignment> ::= "SYMBOL" <assign> <symbol_value> [<whitespace>] ";" <line_end> ;
<source_from_assignment>   ::= "FROM" <assign> <date_value> [<whitespace>] ";" <line_end> ;
<source_to_assignment>     ::= "TO" <assign> <date_value> [<whitespace>] ";" <line_end> ;
<source_workers_assignment> ::= "WORKERS" <assign> <unsigned_int> [<whitespace>] ";" <line_end> ;
<source_force_rebuild_cache_assignment> ::= "FORCE_REBUILD_CACHE" <assign> <bool_value> [<whitespace>] ";" <line_end> ;
<source_range_warn_batches_assignment> ::= "RANGE_WARN_BATCHES" <assign> <unsigned_int> [<whitespace>] ";" <line_end> ;
<source_sources_dsl_file_assignment> ::= "SOURCES_DSL_FILE" <assign> <file_path_value> [<whitespace>] ";" <line_end> ;
<source_channels_dsl_file_assignment> ::= "CHANNELS_DSL_FILE" <assign> <file_path_value> [<whitespace>] ";" <line_end> ;

<probe_block>            ::= "PROBE" [<whitespace>] [":" [<whitespace>]] <binding_ref> [<whitespace>] "{"
                             <line_end>
                             {<probe_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<probe_assignment>       ::= [<whitespace>] <probe_assignment_core> ;
<probe_assignment_core>  ::= <family_assignment>
                           | <hashimyei_assignment>
                           | <path_assignment>
                           | <probe_runtime_block>
                           | <probe_runtime_assignment> ;
<probe_runtime_block>    ::= "RUNTIME" <assign> "{" <line_end>
                             {<probe_runtime_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<probe_runtime_assignment> ::= [<whitespace>] <probe_runtime_assignment_core> ;
<probe_runtime_assignment_core> ::= <probe_training_window_assignment>
                                  | <probe_report_policy_assignment>
                                  | <probe_objective_assignment> ;
<probe_training_window_assignment> ::= "TRAINING_WINDOW" <assign> <probe_training_window_value> [<whitespace>] ";" <line_end> ;
<probe_report_policy_assignment> ::= "REPORT_POLICY" <assign> <probe_report_policy_value> [<whitespace>] ";" <line_end> ;
<probe_objective_assignment> ::= "OBJECTIVE" <assign> <probe_objective_value> [<whitespace>] ";" <line_end> ;

<sink_block>             ::= "SINK" [<whitespace>] [":" [<whitespace>]] <binding_ref> [<whitespace>] "{"
                             <line_end>
                             {<sink_assignment>}
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<sink_assignment>        ::= [<whitespace>] <sink_assignment_core> ;
<sink_assignment_core>   ::= <family_assignment> | <path_assignment> ;

<family_assignment>      ::= "FAMILY" <assign> <path_value> [<whitespace>] ";" <line_end> ;
<hashimyei_assignment>   ::= "HASHIMYEI" <assign> <hashimyei_id> [<whitespace>] ";" <line_end> ;
<path_assignment>        ::= "PATH" <assign> <path_value> [<whitespace>] ";" <line_end> ;

<wave_name>              ::= <id_value> ;
<path_value>             ::= <id_value> ;
<hashimyei_id>           ::= "0x" <hex_digit> {<hex_digit>}
                           | "0X" <hex_digit> {<hex_digit>} ;
<id_value>               ::= <id_char> {<id_char>} ;
<mode_value>             ::= <mode_atom> { [<whitespace>] <mode_join> [<whitespace>] <mode_atom> } ;
<mode_atom>              ::= "run" | "train" | "debug" | <unsigned_int> | <hex_literal> | <bin_literal> ;
<mode_join>              ::= "|" | "," | "+" | "^" ;
<determinism_value>      ::= "deterministic" | "non_deterministic" | "nondeterministic" | "non-deterministic" | "stochastic" ;
<sampler_value>          ::= "sequential" | "random" | "SequentialSampler" | "RandomSampler" ;
<probe_training_window_value> ::= "incoming_batch" ;
<probe_report_policy_value> ::= "epoch_end_log" ;
<probe_objective_value>  ::= "future_target_dims_nll" ;
<bool_value>             ::= "true" | "false" | "1" | "0" ;
<symbol_value>           ::= <symbol_char> {<symbol_char>} ;
<date_value>             ::= <digit><digit> "." <digit><digit> "." <digit><digit><digit><digit> ;
<unsigned_int>           ::= <digit> {<digit>} ;
<hex_literal>            ::= "0x" <hex_digit> {<hex_digit>}
                           | "0X" <hex_digit> {<hex_digit>} ;
<bin_literal>            ::= "0b" <bin_digit> {<bin_digit>}
                           | "0B" <bin_digit> {<bin_digit>} ;
<file_path_value>        ::= <file_path_char> {<file_path_char>} ;

<id_char>                ::= <letter> | <digit> | "_" | "." | "-" ;
<symbol_char>            ::= <letter> | <digit> | "_" | "." | "-" ;
<file_path_char>         ::= <letter> | <digit> | "_" | "." | "-" | "/" | ":" ;

<line_end>               ::= [<whitespace>] <break_block> ;
<break_block>            ::= {<newline>} ;
<whitespace>             ::= {<empty>} ;
<letter>                 ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ;
<hex_digit>              ::= <digit> | "a" | "b" | "c" | "d" | "e" | "f" | "A" | "B" | "C" | "D" | "E" | "F" ;
<bin_digit>              ::= "0" | "1" ;
<digit>                  ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
<newline>                ::= "\n" | "\r\n" ;
<empty>                  ::= " " | "\t" ;
