<instruction>                ::= <contract_begin> <line_end>
                                 <dock_section>
                                 <assembly_section>
                                 <contract_end> <line_end> ;

<dock_section>               ::= [<whitespace>] "DOCK" [<whitespace>] "{"
                                 <line_end>
                                 {<dock_entry>}
                                 [<whitespace>] "}" <line_end> ;

<dock_entry>                 ::= <contract_variable_decl>
                               | <instrument_signature_decl> ;

<assembly_section>           ::= [<whitespace>] "ASSEMBLY" [<whitespace>] "{"
                                 <line_end>
                                 {<assembly_entry>}
                                 [<whitespace>] "}" <line_end> ;

<assembly_entry>             ::= <contract_variable_decl>
                               | <circuit_file_decl>
                               | <acknowledge_decl> ;

<contract_begin>             ::= "-----BEGIN IITEPI CONTRACT-----" ;
<contract_end>               ::= "-----END IITEPI CONTRACT-----" ;

<circuit_file_decl>          ::= [<whitespace>] "CIRCUIT_FILE"
                                 [<whitespace>] ":"
                                 [<whitespace>] <path_value>
                                 [<whitespace>] ";" <line_end> ;

<contract_variable_decl>     ::= [<whitespace>] <contract_variable_name>
                                 [<whitespace>] "="
                                 [<whitespace>] <path_value>
                                 [<whitespace>] ";" <line_end> ;

<acknowledge_decl>           ::= [<whitespace>] "AKNOWLEDGE"
                                 [<whitespace>] ":"
                                 [<whitespace>] <alias_value>
                                 [<whitespace>] "="
                                 [<whitespace>] <family_value>
                                 [<whitespace>] ";" <line_end> ;

<instrument_signature_decl>  ::= [<whitespace>] "INSTRUMENT_SIGNATURE"
                                 [<whitespace>] "<"
                                 [<whitespace>] <alias_value>
                                 [<whitespace>] ">"
                                 [<whitespace>] "{"
                                 <line_end>
                                 [<whitespace>] "SYMBOL" [<whitespace>] ":"
                                 [<whitespace>] <instrument_signature_value>
                                 [<whitespace>] ";" <line_end>
                                 [<whitespace>] "RECORD_TYPE" [<whitespace>] ":"
                                 [<whitespace>] <instrument_signature_value>
                                 [<whitespace>] ";" <line_end>
                                 [<whitespace>] "MARKET_TYPE" [<whitespace>] ":"
                                 [<whitespace>] <instrument_signature_value>
                                 [<whitespace>] ";" <line_end>
                                 [<whitespace>] "VENUE" [<whitespace>] ":"
                                 [<whitespace>] <instrument_signature_value>
                                 [<whitespace>] ";" <line_end>
                                 [<whitespace>] "BASE_ASSET" [<whitespace>] ":"
                                 [<whitespace>] <instrument_signature_value>
                                 [<whitespace>] ";" <line_end>
                                 [<whitespace>] "QUOTE_ASSET" [<whitespace>] ":"
                                 [<whitespace>] <instrument_signature_value>
                                 [<whitespace>] ";" <line_end>
                                 [<whitespace>] "}" [<whitespace>] ";"
                                 <line_end> ;

<alias_value>                ::= <id_char> {<id_char>} ;
<contract_variable_name>     ::= "_" "_" <id_char> {<id_char>} ;
<family_value>               ::= <id_char> {<id_char>} ;
<instrument_signature_value> ::= "ANY" | <family_value> ;
<path_value>                 ::= <family_value> | <quoted_text> | <list_value> ;
<list_value>                 ::= "[" [<list_items>] "]" ;
<list_items>                 ::= <family_value> { [<whitespace>] "," [<whitespace>] <family_value> } ;
<quoted_text>                ::= "\"" {<quoted_char>} "\"" ;
<quoted_char>                ::= <id_char> | "/" | ":" | "\\" | "." | "-" | "_" | " " ;

<line_end>                   ::= [<whitespace>] <break_block> ;
<break_block>                ::= {<newline>} ;
<whitespace>                 ::= {<empty>} ;
<id_char>                    ::= <letter> | <digit> | "_" | "." | "-" ;
<letter>                     ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ;
<digit>                      ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
<newline>                    ::= "\n" | "\r\n" ;
<empty>                      ::= " " | "\t" ;
