<instruction>               ::= [<line_list>] ;
<line_list>                 ::= <line> [<line_list>] ;

<line>                      ::= <campaign_line>
                              | <objective_md_line>
                              | <guidance_md_line>
                              | <name_line>
                              | <loop_id_line>
                              | <blank_line> ;

<campaign_line>             ::= [<whitespace>] "campaign_dsl_path"
                                [<whitespace>] ":" [<whitespace>] "path"
                                [<whitespace>] "=" [<whitespace>] <value>
                                [<whitespace>] [ ";" ] <line_end> ;

<objective_md_line>         ::= [<whitespace>] "objective_md_path"
                                [<whitespace>] ":" [<whitespace>] "path"
                                [<whitespace>] "=" [<whitespace>] <value>
                                [<whitespace>] [ ";" ] <line_end> ;

<guidance_md_line>          ::= [<whitespace>] "guidance_md_path"
                                [<whitespace>] ":" [<whitespace>] "path"
                                [<whitespace>] "=" [<whitespace>] <value>
                                [<whitespace>] [ ";" ] <line_end> ;

<name_line>                 ::= [<whitespace>] "objective_name"
                                [<whitespace>] ":" [<whitespace>] "str"
                                [<whitespace>] "=" [<whitespace>] <value>
                                [<whitespace>] [ ";" ] <line_end> ;

<loop_id_line>              ::= [<whitespace>] "loop_id"
                                [<whitespace>] ":" [<whitespace>] "str"
                                [<whitespace>] "=" [<whitespace>] <value>
                                [<whitespace>] [ ";" ] <line_end> ;

<blank_line>                ::= [<whitespace>] <line_end> ;

<value>                     ::= <quoted_text> | <bare_value> ;
<quoted_text>               ::= "\"" [<quoted_chars>] "\"" ;
<quoted_chars>              ::= <quoted_char> [<quoted_chars>] ;
<quoted_char>               ::= <letter> | <digit> | <symbol> | <space_char> ;

<bare_value>                ::= <bare_char> [<bare_value>] ;
<bare_char>                 ::= <letter> | <digit> | <symbol> | <space_char> ;

<symbol>                    ::= "." | "," | ":" | ";" | "-" | "_" | "\\" | "/"
                              | "[" | "]" | "(" | ")" | "{" | "}" | "|" | "'"
                              | "+" | "*" | "?" | "!" | "<" | ">" | "=" | "@";

<line_end>                  ::= <newline> ;
<whitespace>                ::= <space_char> [<whitespace>] ;
<space_char>                ::= " " | "\t" ;
<newline>                   ::= "\n" | "\r\n" ;
<letter>                    ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H"
                              | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P"
                              | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X"
                              | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f"
                              | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n"
                              | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v"
                              | "w" | "x" | "y" | "z" ;
<digit>                     ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7"
                              | "8" | "9" ;
