<instruction>            ::= [<comment>] <csv_policy_block> <data_analytics_policy_block> <instrument_table> ;
<csv_policy_block>       ::= "CSV_POLICY" [<whitespace>] "{" <line_end>
                             <csv_bootstrap_assignment>
                             <csv_step_abs_tol_assignment>
                             <csv_step_rel_tol_assignment>
                             [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<csv_bootstrap_assignment> ::= [<whitespace>] "CSV_BOOTSTRAP_DELTAS" [<whitespace>] "=" [<whitespace>] <policy_unsigned_int> [<whitespace>] ";" <line_end> ;
<csv_step_abs_tol_assignment> ::= [<whitespace>] "CSV_STEP_ABS_TOL" [<whitespace>] "=" [<whitespace>] <policy_float> [<whitespace>] ";" <line_end> ;
<csv_step_rel_tol_assignment> ::= [<whitespace>] "CSV_STEP_REL_TOL" [<whitespace>] "=" [<whitespace>] <policy_float> [<whitespace>] ";" <line_end> ;
<data_analytics_policy_block> ::= "DATA_ANALYTICS_POLICY" [<whitespace>] "{" <line_end>
                                   <data_analytics_max_samples_assignment>
                                   <data_analytics_max_features_assignment>
                                   <data_analytics_mask_epsilon_assignment>
                                   <data_analytics_standardize_epsilon_assignment>
                                   [<whitespace>] "}" [<whitespace>] ";" <line_end> ;
<data_analytics_max_samples_assignment> ::= [<whitespace>] "MAX_SAMPLES" [<whitespace>] "=" [<whitespace>] <policy_unsigned_int> [<whitespace>] ";" <line_end> ;
<data_analytics_max_features_assignment> ::= [<whitespace>] "MAX_FEATURES" [<whitespace>] "=" [<whitespace>] <policy_unsigned_int> [<whitespace>] ";" <line_end> ;
<data_analytics_mask_epsilon_assignment> ::= [<whitespace>] "MASK_EPSILON" [<whitespace>] "=" [<whitespace>] <policy_float> [<whitespace>] ";" <line_end> ;
<data_analytics_standardize_epsilon_assignment> ::= [<whitespace>] "STANDARDIZE_EPSILON" [<whitespace>] "=" [<whitespace>] <policy_float> [<whitespace>] ";" <line_end> ;
<instrument_table>       ::= <table_top_line> <instrument_header_line> <table_divider_line> {<instrument_form>} <table_bottom_line> ;
<instrument_header_line> ::= "|" <whitespace> "instrument" <whitespace> "|" <whitespace> "interval" <whitespace> "|" <whitespace> "record_type" <whitespace> "|" <whitespace> "market_type" <whitespace> "|" <whitespace> "venue" <whitespace> "|" <whitespace> "base_asset" <whitespace> "|" <whitespace> "quote_asset" <whitespace> "|" <whitespace> "source" <whitespace> "|" <break_block> ;
<instrument_form>        ::= "|" <whitespace> <instrument> <whitespace> "|" <whitespace> <interval> <whitespace> "|" <whitespace> <record_type> <whitespace> "|" <whitespace> <market_type> <whitespace> "|" <whitespace> <venue> <whitespace> "|" <whitespace> <base_asset> <whitespace> "|" <whitespace> <quote_asset> <whitespace> "|" <whitespace> <source> "|" <break_block> ;
<table_top_line>         ::= "/" {<frame_char>} "\\" <line_end> ;
<table_divider_line>     ::= "|" {<frame_char>} "|" <line_end> ;
<table_bottom_line>      ::= "\\" {<frame_char>} "/" [<line_end>] ;
<comment>                ::= "/*" {<character>} "*/" <line_end> ;
<source>                 ::= <file_path> ;
<policy_unsigned_int>    ::= <digit> {<digit>} ;
<policy_float>           ::= <policy_float_char> {<policy_float_char>} ;
<policy_float_char>      ::= <letter> | <digit> | "." | "+" | "-" ;
<file_path>              ::= {<literal>} ;
<break_block>            ::= {<newline>} ;
<line_end>               ::= [<whitespace>] <break_block> ;
<character>              ::= <whitespace> | <letter> | <newline> | <number> | <special> | <super_special> ;
<literal>                ::= <whitespace> | <letter> | <number> | <special> ;
<whitespace>             ::= {<empty>} ;
<instrument>             ::= <family_value> ;
<record_type>            ::= "kline" | "trade" | "basic" ;
<market_type>            ::= <family_value> ;
<venue>                  ::= <family_value> ;
<base_asset>             ::= <family_value> ;
<quote_asset>            ::= <family_value> ;
<family_value>           ::= <id_char> {<id_char>} ;
<id_char>                ::= <letter> | <digit> | "_" | "." | "-" ;
<interval>               ::= "constant" | "sine" | "triangular" | "1s" | "1m" | "3m" | "5m" | "15m" | "30m" | "1h" | "2h" | "4h" | "6h" | "8h" | "12h" | "1d" | "3d" | "1w" | "1M" ;
<special>                ::= "." | "," | ":" | ";" | "-" | "_" | "\\" | "/" | "(" | ")" | "[" | "]" | "=" | ">" | "<" | "!" | "?" | "+" ;
<super_special>          ::= "|" ;
<letter>                 ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";
<digit>                  ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
<number>                 ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "." ;
<newline>                ::= "\n" | "\r\n" ;
<empty>                  ::= " " | "\t" ;
<frame_char>             ::= "-" ;
