<instruction>            ::= {<table>} ;
<table>                  ::= <comment> <table_header> <table_top_line> <header_line> <table_divider_line> {<item_line>} <table_bottom_line>;
<comment>                ::= "/*" {<character>} "*/" <break_block> ;
<table_header>           ::= "[" <whitespace> <table_title> <whitespace> "]" <break_block> ;
<table_top_line>         ::= "/" {<frame_char>} "\" <break_block> ;
<header_line>            ::= <line_start> {<cell>} <line_ending> ;
<table_divider_line>     ::= <div> {<frame_char>} <div> <break_block> ;
<item_line>              ::= <line_start> {<cell>} <line_ending> ;
<table_bottom_line>      ::= "\" {<frame_char>} "/" [<break_block>] ;
<cell>                   ::= [<div>] <whitespace> <field> [<whitespace>] ;
<line_start>             ::= <div> ;
<line_ending>            ::= <div> <break_block> ;
<table_title>            ::= {<literal>} ;
<field>                  ::= {<literal>} ;
<break_block>            ::= {<newline>} ;
<character>              ::= <whitespace> | <letter> | <number> | <special> | <super_special> | <newline> ;
<literal>                ::= <letter> | <number> | <special> ;
<whitespace>             ::= {<empty>} ;
<div>                    ::= "|" ;
<frame_char>             ::= "-" ;
<special>                ::= "." | "," | ":" | ";" | "-" | "_" | "\" | "/" ;
<super_special>          ::= "(" | ")" | "[" | "]" ;
<letter>                 ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";
<number>                 ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
<newline>                ::= "\n" | "\r\n" ;
<empty>                  ::= " " | "\t" ;
