#include "hero_config_tools_config_file_ops_private_validation.cpp"
#include "hero_config_tools_config_file_ops_private_default_temp.cpp"
#include "hero_config_tools_config_file_ops_private_objective.cpp"
