#include "hero_marshal_tools_private_checkpoints_session.cpp"
#include "hero_marshal_tools_private_checkpoints_human.cpp"
#include "hero_marshal_tools_private_checkpoints_decision.cpp"
#include "hero_marshal_tools_private_checkpoints_inputs.cpp"
