#include "hashimyei_catalog_private_core_utils.cpp"
#include "hashimyei_catalog_private_core_founding_bundle.cpp"
#include "hashimyei_catalog_private_core_catalog_helpers.cpp"
#include "hashimyei_catalog_private_core_run_manifest.cpp"
#include "hashimyei_catalog_private_core_component_manifest.cpp"
#include "hashimyei_catalog_private_core_save.cpp"
