<instruction> ::= "CAJTUCU_EXECUTION_PAPER" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<assignment> ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<key> ::= "VERSION" | "COMPONENT_ASSEMBLY_ID" | "INPUT_INTENT_SCHEMA" | "OUTPUT_TRACE_SCHEMA" | "LEDGER_SCHEMA" | "BACKEND_KIND" | "ACTION_SOURCE" | "MARKET_SOURCE_POLICY" | "SYNTHETIC_MARKET_SOURCE_POLICY" | "ROUTE_POLICY" | "RESERVE_NODE_POLICY" | "EXECUTION_ORDER_POLICY" | "ORDER_MODEL" | "FILL_PRICE_MODEL" | "INVALID_SELL_PRICE_POLICY" | "FEE_MODEL" | "MIN_NOTIONAL_POLICY" | "MAX_NOTIONAL_POLICY" | "PARTIAL_FILL_POLICY" | "LEDGER_POLICY" | "MARK_TO_MARKET_POLICY" | "EQUITY_MISMATCH_POLICY" | "TRACE_POLICY" | "EXECUTION_AUTHORITY" | "LIVE_EXECUTION_ALLOWED" | "BROKER_CREDENTIALS_ALLOWED" | "NETWORK_IO_ALLOWED" | "DEFAULT_ALLOW_PARTIAL_FILLS" | "DEFAULT_ALLOW_NEGATIVE_BASE_RESERVE" | "DEFAULT_ALLOW_SYNTHETIC_DIRECT_EDGES" | "DEFAULT_EQUITY_MISMATCH_TOLERANCE" | "DEFAULT_EQUITY_MISMATCH_FAIL_TOLERANCE" | "EPS" ;
<value> ::= <value_char> {<value_char>} ;
<value_char> ::= <letter> | <digit> | "_" | "." | "-" | "+" ;
<line_end> ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace> ::= {<empty>} ;
