<instruction> ::= {<selection>} {<wave_settings>} ;
<selection>   ::= "WAVE_SELECTION" [<whitespace>] "{" <line_end> {<selection_assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<wave_settings> ::= "WAVE_SETTINGS" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<selection_assignment> ::= [<whitespace>] <selection_key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<assignment>  ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<selection_key> ::= "ACTIVE_WAVE_ID" ;
<key>         ::= "WAVE_ID" | "COMPATIBLE_PROTOCOLS" | "TARGET" | "MODE" | "JOB_KIND" | "POLICY_ID" | "POLICY_KIND" | "TRAINING_SCHEDULE_MODE" | "LIVE_EXECUTION_ALLOWED" | "SOURCE_CURSOR_KIND" | "SOURCE_CURSOR_SCOPE" | "SOURCE_RANGE" | "SOURCE_ORDER" | "ANCHOR_INDEX_BEGIN" | "ANCHOR_INDEX_END" | "SOURCE_KEY_BEGIN" | "SOURCE_KEY_END" | "ANCHOR_KEY_BEGIN" | "ANCHOR_KEY_END" ;
<value>       ::= <value_char> {<value_char>} ;
<value_char>  ::= <letter> | <digit> | "_" | "." | "-" | "|" | "," | "+" ;
<line_end>    ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace>  ::= {<empty>} ;
