<instruction> ::= "REPLAY_ENVIRONMENT" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<assignment> ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<key> ::= "VERSION" | "COMPONENT_ASSEMBLY_ID" | "WORLD_MODE" | "API_CONTRACT" | "SPAWN_MODEL" | "RANGE_SOURCE" | "SOURCE_RANGE_POLICY" | "SOURCE_ORDER_POLICY" | "RANGE_RESOLUTION" | "OBSERVATION_TIME_LAW" | "REALIZATION_REVEAL" | "REALIZATION_KEY_POLICY" | "ACTION_KIND" | "ACTION_SCHEMA_ID" | "ACTION_TIME_POLICY" | "RESERVE_NODE_POLICY" | "GRAPH_NODE_UNIVERSE_POLICY" | "REWARD_POLICY" | "PROJECTION_VALIDATION" | "REALIZED_RETURN_TRUTH" | "POLICY_SURFACE" | "ACTION_POLICY_IDENTITY" | "INITIAL_POLICY_KIND" | "EXPERIMENT_TASK_IDENTITY" | "EXPERIMENT_RUN_IDENTITY" | "STEP_ARTIFACT_IDENTITY" | "EXPERIMENT_REPORT_COUNT_POLICY" | "ARTIFACT_SCHEMA" | "LATTICE_FACT_FAMILY" | "LATTICE_TARGET" | "REQUIRE_RESOLVED_CURSOR" | "REQUIRE_NO_FUTURE_LEAKAGE" | "REQUIRE_PROJECTION_VALIDATION" | "REPLAY_EXECUTOR" | "ALLOCATION_AUTHORITY" | "EXECUTION_AUTHORITY" | "LIVE_CAPITAL_ALLOWED" | "DEFAULT_MAX_PARALLEL_JOBS" ;
<value> ::= <value_char> {<value_char>} ;
<value_char> ::= <letter> | <digit> | "_" | "." | "-" | "+" ;
<line_end> ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace> ::= {<empty>} ;
