<instruction> ::= <policy_block> {<split_block>} ;
<policy_block> ::= "LATTICE_SPLIT_POLICY" [<whitespace>] "{" <line_end> {<policy_assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<split_block> ::= "LATTICE_SPLIT" [<whitespace>] "{" <line_end> {<split_assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<policy_assignment> ::= [<whitespace>] <policy_key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<split_assignment> ::= [<whitespace>] <split_key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<policy_key> ::= "POLICY_ID" | "CURSOR_DOMAIN" | "PURGE_LEFT_CONTEXT" | "PURGE_RIGHT_FUTURE" ;
<split_key> ::= "SPLIT_ID" | "ROLE" | "ANCHOR_INDEX_BEGIN" | "ANCHOR_INDEX_END" | "ALLOW_USES" | "PROTECT_FROM_USES" | "PROTECT_REQUIRES_MUTATED_COMPONENT" ;
<value> ::= <value_char> {<value_char>} ;
<value_char> ::= <letter> | <digit> | "_" | "." | "-" | "|" | "," | "+" ;
<line_end> ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace> ::= {<empty>} ;
