<instruction> ::= "GRAPH_NODE_ALLOCATION_FEATURES" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<assignment>  ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<key>         ::= "VERSION" | "POLICY_INPUT_SCHEMA" | "NODE_FEATURE_DIM" | "NODE_FEATURE_NAMES" | "NODE_FEATURE_TRANSFORMS" | "NODE_FEATURE_DEFAULT_POLICY" | "NODE_FEATURE_CLIPPING_POLICY" | "GLOBAL_FEATURE_DIM" | "GLOBAL_FEATURE_NAMES" | "GLOBAL_FEATURE_TRANSFORMS" | "GLOBAL_FEATURE_DEFAULT_POLICY" | "GLOBAL_FEATURE_CLIPPING_POLICY" | "RISK_FEATURE_BLOCK" | "RISK_FEATURE_DIM" | "RISK_FEATURE_NAMES" | "RISK_FEATURE_TRANSFORMS" | "RISK_FEATURE_DEFAULT_POLICY" | "RISK_FEATURE_CLIPPING_POLICY" | "EVIDENCE_ONLY_FIELDS" | "RAW_MDN_INPUT_ALLOWED" | "FULL_SCENARIO_BANK_INPUT_ALLOWED" ;
<value>       ::= <value_char> {<value_char>} ;
<value_char>  ::= <letter> | <digit> | "_" | "." | "-" | "+" | "," ;
<line_end>    ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace>  ::= {<empty>} ;
