<instruction> ::= "VICREG" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<assignment>  ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<key>         ::= "VERSION" | "COMPONENT_ID" | "INPUT_ROUTE" | "INPUT_WIDTH" | "MASK_PROFILE" | "REQUIRED_FEATURE_COORDS" | "DTYPE" | "DEVICE" ;
<value>       ::= <value_char> {<value_char>} ;
<value_char>  ::= <letter> | <digit> | "_" | "." | "-" | "," | ":" | "+" ;
<line_end>    ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace>  ::= {<empty>} ;
