<instruction> ::= "GRAPH_NODE_ALLOCATION_NET" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<assignment>  ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<key>         ::= "VERSION" | "POLICY_INPUT_SCHEMA" | "POLICY_INPUT_FEATURE_MANIFEST" | "INPUT_NODE_FEATURE_DIM" | "INPUT_GLOBAL_FEATURE_DIM" | "INPUT_RISK_FEATURE_DIM" | "NODE_ENCODER_LAYERS" | "NODE_ENCODER_HIDDEN_DIM" | "GLOBAL_ENCODER_LAYERS" | "GLOBAL_ENCODER_HIDDEN_DIM" | "RISK_ENCODER_LAYERS" | "RISK_ENCODER_HIDDEN_DIM" | "POOLING" | "FUSION_HIDDEN_DIM" | "FUSION_LAYERS" | "ACTIVATION" | "NORMALIZATION" | "DROPOUT" | "SHARE_ENCODER" | "SEPARATE_ACTOR_CRITIC_HEADS" | "POLICY_HEAD_HIDDEN_DIM" | "VALUE_HEAD_HIDDEN_DIM" | "OUTPUT_HEAD" | "VALUE_HEAD" | "DIRICHLET_CONCENTRATION_HEAD" | "DIRICHLET_ALPHA_FLOOR" | "DIRICHLET_TOTAL_CONCENTRATION_MIN" | "DIRICHLET_TOTAL_CONCENTRATION_MAX" | "LOGISTIC_NORMAL_CANDIDATE" | "LOGISTIC_NORMAL_STD_HEAD" | "LOGISTIC_NORMAL_LOG_STD_MIN" | "LOGISTIC_NORMAL_LOG_STD_MAX" | "LOGISTIC_NORMAL_COORDINATE_POLICY" | "LOGISTIC_NORMAL_ENTROPY_KIND" ;
<value>       ::= <value_char> {<value_char>} ;
<value_char>  ::= <letter> | <digit> | "_" | "." | "-" | "+" ;
<line_end>    ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace>  ::= {<empty>} ;
