<instruction> ::= "MDN" [<whitespace>] "{" <line_end> {<assignment>} [<whitespace>] "}" [<whitespace>] ";" [<line_end>] ;
<assignment>  ::= [<whitespace>] <key> [<whitespace>] "=" [<whitespace>] <value> [<whitespace>] ";" <line_end> ;
<key>         ::= "VERSION" | "COMPONENT_ASSEMBLY_ID" | "INPUT_REPRESENTATION_ASSEMBLY_ID" | "CONTEXT_MODE" | "TARGET_DOMAIN" | "TARGET_COORDS" | "TARGET_MASK_POLICY" | "ACTIVITY_TARGET" | "SIGMA_MIN" | "SIGMA_MAX" | "EPS" ;
<value>       ::= <value_char> {<value_char>} ;
<value_char>  ::= <letter> | <digit> | "_" | "." | "-" | "," | "+" ;
<line_end>    ::= [<whitespace>] <break_block> ;
<break_block> ::= {<newline>} ;
<whitespace>  ::= {<empty>} ;
