ROOT_PATH := ../../..
include $(ROOT_PATH)/Makefile.config

.DEFAULT_GOAL := all

.PHONY: all api

api:
	@printf "[KIKIJYEBA:PROTOCOL] header-only graph-first protocol surface\n"

all: api
	@$(LOG_SUCCESS)
