# General settings
GXX := g++
GXX_VERSION := c++20
GXX_FLAGS := -std=$(GXX_VERSION) -Wno-unused-function -Wall -g -MMD -MP -Og 
GXX_SECURITY := -fstack-protector-strong -pie -fPIE -D_FORTIFY_SOURCE=2 

GXX_FLAGS := $(GXX_FLAGS) $(GXX_SECURITY)

# Path settings
OUTPUT_PATH := $(ROOT_PATH)/build
SRC_PATH := $(ROOT_PATH)/src
TESTS_PATH := $(ROOT_PATH)/tests
CONFIG_PATH := $(ROOT_PATH)/config

# External Paths
EXTERNAL_LIBS_PATH := /cuwacunu/external
LIBTORCH_PATH := $(EXTERNAL_LIBS_PATH)/libtorch
LIBCUDA_PATH := /usr/local/cuda-12.1
SSL_PATH := /usr
LIBCURL_PATH := /usr
NCURSES_PATH := 

USUAL_INCLUDE_PATHS := -I$(ROOT_PATH)/ -I$(ROOT_PATH)/include -I$(ROOT_PATH)/include/torch_compat
TORCH_INCLUDE_PATHS := -I$(LIBTORCH_PATH)/include -I$(LIBTORCH_PATH)/include/torch/csrc/api/include -I$(LIBCUDA_PATH)/include
SSL_INCLUDE_PATHS := -I$(SSL_PATH)/include -L$(SSL_PATH)/lib
LIBCURL_INCLUDE_PATHS := -I$(LIBCURL_PATH)/include
NCURSES_INCLUDE_PATHS := 

# Linkage settings
USUAL_LD_FLAGS := -lstdc++ -lpthread -lm 
TORCH_LD_FLAGS := -L$(LIBTORCH_PATH)/lib -L$(LIBCUDA_PATH)/lib64 -Wl,-rpath,$(LIBTORCH_PATH)/lib -ltorch_cuda -lc10_cuda -ltorch_cpu -ltorch -lcudnn -lc10 -lcuda -lcudart 
SSL_LD_FLAGS := -L$(SSL_PATH)/lib/x86_64-linux-gnu/ -lcrypto -lssl
LIBCURL_LD_LAGS := -lcurl 
NCURSES_LD_LAGS := -lncursesw -lncurses 

# Color settings for echo commands
COLOR_RED 	:= \033[31m
COLOR_GREEN := \033[32m
COLOR_BLUE := \033[34m
COLOR_YELLOW := \033[33m
COLOR_ORANGE := \033[38;5;208m
COLOR_RESET := \033[0m

# Logging commands
LOG_START = echo "$(COLOR_YELLOW)Building $(@F)...$(COLOR_RESET)"
LOG_END =  echo "$(COLOR_GREEN)     Built done $(@F)...$(COLOR_RESET)" || echo "$(COLOR_RED)     Build $(@F) failed with error code $$? $(COLOR_RESET)"
LOG_SUCCESS = echo "$(COLOR_GREEN)$@ built $(HERE_PATH) successfully.$(COLOR_RESET)"

# shred deletion of deprecated compiled files protect against cached debuging versions unthought vulnerabilities
LOCAL_CLEAN = { [ -f $@ ] && shred -u $@ || true; }

# Debug
PLAIN = 
GDB = gdb -ex run 
VALGRIND = valgrind --leak-check=full -s  --show-leak-kinds=all --suppressions=$(CONFIG_PATH)/valgrind.supp --gen-suppressions=all --log-file=/cuwacunu/src/valgrind.log 

RUN_MODE = $(GDB)

# Export
export GXX \
	GXX_VERSION \
	GXX_FLAGS \
	ROOT_PATH \
	OUTPUT_PATH \
	SRC_PATH \
	LIBTORCH_PATH \
	LIBCUDA_PATH \
	LIBCURL_INCLUDE_PATHS \
	USUAL_INCLUDE_PATHS \
	TORCH_INCLUDE_PATHS \
	USUAL_LD_FLAGS \
	TORCH_LD_FLAGS \
	SSL_LD_FLAGS \
	LIBCURL_LD_LAGS \
	COLOR_RED \
	COLOR_GREEN \
	COLOR_RESET \
	VALGRIND \
	GDB \
	LOG_INFO \
	LOG_SUCCESS

-include $(wildcard $(OUTPUT_PATH)/*.d)